apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Chart.Name }}-proxy-agones-cluster-role-binding
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: quarkus
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: {{ default "agones-sdk" .Values.agones.serviceaccount.sdk.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Chart.Name }}-proxy
    namespace: {{ .Release.Namespace }}
