# build properties
org.gradle.parallel=true
org.gradle.welcome=never

# project properties
group=dev.marfien.minecraftonk8s
version=1.0.0

# Quarkus properties
quarkusPluginId=io.quarkus
quarkusPluginVersion=3.10.2
quarkusPlatformGroupId=io.quarkus.platform
quarkusPlatformArtifactId=quarkus-bom
quarkusPlatformVersion=3.10.2
