#Gradle properties
#Wed Jul 10 22:23:21 CEST 2024
groupId=dev.marfien.minecraftonk8s
version=1.0.0
javaVersion=21
# This is the minimum supported Java version which will be supported by the client projects
# Java 8 is especially used in earlier versions of Minecraft, e.g. 1.8
minimumSupportedJavaVersion=8
org.gradle.parallel=true
org.gradle.welcome=never
