[versions]
grpc = "1.61.1"

[libraries]
grpc-netty = { group = "io.grpc", name = "grpc-netty", version.ref = "grpc" }
grpc-stub = { group = "io.grpc", name = "grpc-netty", version.ref = "grpc" }
grpc-protobuf = { group = "io.grpc", name = "grpc-netty", version.ref = "grpc" }

agones4j = { group = "com.github.infumia", name = "agones4j", version = "1.0.3" }
kubernetes-client = { group = "io.fabric8", name = "kubernetes-client", version = "6.12.1" }
kubernetes-crdsgen = { group = "io.fabric8", name = "crd-generator-apt", version = "6.12.1" }
