rbac:
  enabled: true

serviceAccounts:
  operator:
    name: "minecraft-on-k8s-operator"
  proxy:
    name: "minecraft-on-k8s-proxy"

minecraftservers:
  allocation:
    defaultStrategy: "players"

proxyfleets:
  allocation:
    defaultStrategy: "players"

operator:
  image:
    repository: "ghcr.io/marfien/mc-on-k8s/operator"
    tag: "@project.version@"
  imagePullPolicy: "Always"
  imagePullSecrets: []
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  nodeSelector: {}
  prometheus:
    enabled: true
    path: "/metrics"

agones:
  gameservers:
    namespaces: ["default"]
