---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  annotations:
    app.quarkus.io/quarkus-version: "3.10.2"
    app.quarkus.io/commit-id: "4a35b5887e08d00a41cec5994cb0738aafe0ef10"
    app.quarkus.io/vcs-uri: "https://github.com/Marfien/mc-on-k8s.git"
    app.quarkus.io/build-timestamp: "2024-07-08 - 15:52:36 +0000"
  labels:
    app.kubernetes.io/name: "operator"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "quarkus"
  name: "operator"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
      app.kubernetes.io/name: "operator"
  template:
    metadata:
      annotations:
        app.quarkus.io/quarkus-version: "3.10.2"
        app.quarkus.io/commit-id: "4a35b5887e08d00a41cec5994cb0738aafe0ef10"
        app.quarkus.io/vcs-uri: "https://github.com/Marfien/mc-on-k8s.git"
        app.quarkus.io/build-timestamp: "2024-07-08 - 15:52:36 +0000"
      labels:
        app.kubernetes.io/managed-by: "quarkus"
        app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
        app.kubernetes.io/name: "operator"
    spec:
    {{- with .Values.operator.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      nodeSelector:
        {{- toYaml .Values.operator.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.operator.affinity | nindent 8 }}
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "QUARKUS_OPERATOR_SDK_CONTROLLERS_MINECRAFTPROXYFLEETRECONCILER_NAMESPACES"
          value: {{ .Values.agones.gameservers.namespaces }}
        - name: "QUARKUS_OPERATOR_SDK_CONTROLLERS_MINECRAFTSERVERRECONCILER_NAMESPACES"
          value: {{ .Values.agones.gameservers.namespaces }}
        - name: "QUARKUS_OPERATOR_SDK_CONTROLLERS_MINECRAFTSERVERFLEETRECONCILER_NAMESPACES"
          value: {{ .Values.agones.gameservers.namespaces }}
        - name: "MINECRAFT_SERVER_ALLOCATION_DEFAULTSTRATEGY"
          value: {{ .Values.minecraftservers.allocation.defaultStrategy }}
        - name: "PROXY_FLEET_ALLOCATION_DEFAULTSTRATEGY"
          value: {{ .Values.proxyfleets.allocation.defaultStrategy }}
        - name: "PROXY_SERVICE_ACCOUNT"
          value: {{ .Chart.Name }}-proxy
        image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}"
        imagePullPolicy: "{{ .Values.operator.imagePullPolicy }}"
        resources:
          limits:
            cpu: "{{ .Values.operator.resources.limits.cpu }}"
            memory: "{{ .Values.operator.resources.limits.memory }}"
          requests:
            cpu: "{{ .Values.operator.resources.requests.cpu }}"
            memory: "{{ .Values.operator.resources.requests.memory }}"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: "/q/health/live"
            port: 8080
            scheme: "HTTP"
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: "operator"
        ports:
        - containerPort: 8080
          name: "http"
          protocol: "TCP"
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: "/q/health/ready"
            port: 8080
            scheme: "HTTP"
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        startupProbe:
          failureThreshold: 3
          httpGet:
            path: "/q/health/started"
            port: 8080
            scheme: "HTTP"
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
      serviceAccountName: "operator"
