{{- if .Values.rbac.enabled . }}
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRole"
metadata:
  name: "minecraftserverfleetreconciler-cluster-role"
rules:
- apiGroups:
  - "mconk8s.marfien.dev"
  resources:
  - "minecraftserverfleets"
  - "minecraftserverfleets/status"
  - "minecraftserverfleets/finalizers"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "patch"
  - "update"
  - "create"
  - "delete"
- apiGroups:
  - "agones.dev"
  resources:
  - "fleets"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "patch"
  - "update"
  - "delete"
  - "create"
{{- end}}
