name: Build with gradle
run-name: Commit of ${{ github.user  }}

on: [push, pull_request]

env:
  SCRIPT_DIR: ".github/workflows/scripts"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download Dotenv
        uses: actions/download-artifact@v2
        with:
          name: dotenv
      - name: Load Dotenv
        uses: falti/dotenv-action@v0.3.1
        with:
          path: .env
      - uses: actions/checkout@v4
      - name: Setup JDK-17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Build with Gradle
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: chmod +rx $SCRIPT_DIR/gradle_build.sh && $SCRIPT_DIR/gradle_build.sh