name: Build with gradle
run-name: Commit of ${{ github.actor  }} on ${{ github.ref_name }}

on: [push, pull_request]

env:
  SCRIPT_DIR: "./.github/workflows/scripts"

permissions:
  contents: read

jobs:
  env:
    runs-on: ubuntu-latest
    steps:
      - name: Create dotenv
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: ls && chmod +rx $SCRIPT_DIR/env.sh && $SCRIPT_DIR/env.sh
      - name: Upload dotenv
        uses: actions/upload-artifact@v3
        with:
          path: .env
  build:
    runs-on: ubuntu-latest
    needs:
      - env
    steps:
      - name: Download dotenv
        uses: actions/download-artifact@v3
        with:
          name: dotenv
      - name: Load Dotenv
        uses: falti/dotenv-action@v1
        with:
          path: .env
      - uses: actions/checkout@v4
      - name: Setup JDK-17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Build with Gradle
        run: chmod +rx $SCRIPT_DIR/gradle_build.sh && $SCRIPT_DIR/gradle_build.sh