name: Build with gradle
run-name: Commit "${{ github.event.head_commit.message }}" on ${{ github.ref_name }}

on: [push, pull_request]

env:
  SCRIPT_DIR: "./.github/workflows/scripts"

permissions:
  contents: read

jobs:
  env:
    if: ${{ !contains(github.event.head_commit.message, '--skip-ci') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create dotenv
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: chmod +rx $SCRIPT_DIR/env.sh && $SCRIPT_DIR/env.sh
      - name: Upload dotenv
        uses: actions/upload-artifact@v3
        with:
          name: dotenv
          path: .env
  build:
    if: ${{ !contains(github.event.head_commit.message, '--skip-ci') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs:
      - env
    steps:
      - name: Download dotenv
        uses: actions/download-artifact@v3
        with:
          name: dotenv
      - name: Load Dotenv
        uses: xom9ikk/dotenv@v2
      - uses: actions/checkout@v4
      - name: Setup JDK-17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Build with Gradle
        run: chmod +rx $SCRIPT_DIR/gradle_build.sh && $SCRIPT_DIR/gradle_build.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}