#sed -i '' "s/^version=.*$/version=$new_version/" gradle.properties
name: Create Release
run-name: ${{ github.event.inputs.custom-version && format('Creating release for version "{0}"', github.event.inputs.custom-version) || format('Upgrading {0}-version', github.event.inputs.version-upgrade) }}

on:
  workflow_dispatch:
    inputs:
      version-upgrade:
        description: Upgrade version (ignored if 'Custom version' is not empty)
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch
      custom-version:
        description: Custom version
        required: false
        default: ''
        type: string

env:
  SCRIPT_DIR: "./.github/workflows/scripts"

jobs:
  env:
    runs-on: ubuntu-latest
    env:
      INPUT_VERSION_UPGRADE: ${{ github.event.inputs.version-upgrade }}
      INPUT_CUSTOM_VERSION: ${{ github.event.inputs.custom-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotenv
        run: chmod +rx $SCRIPT_DIR/env.sh && $SCRIPT_DIR/env.sh
      - name: Setup dotenv for release
        run: chmod +rx $SCRIPT_DIR/release_version.sh && $SCRIPT_DIR/release_version.sh
      - name: Upload dotenv
        uses: actions/upload-artifact@v3
        with:
          name: dotenv
          path: .env
  update-version:
    runs-on: ubuntu-latest
    needs:
      - env
    permissions:
      contents: write
    steps:
      - name: Download dotenv
        uses: actions/download-artifact@v3
        with:
          name: dotenv
      - name: Load Dotenv
        uses: xom9ikk/dotenv@v2
      - uses: actions/checkout@v4
      - name: Setup git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      - name: Update versions
        env:
          BRANCHES: "main develop"
        run: chmod +rx $SCRIPT_DIR/update_in_branches.sh && $SCRIPT_DIR/update_in_branches.sh
  create-tag:
    runs-on: ubuntu-latest
    needs:
      - update-version
    permissions:
      contents: write
    steps:
      - name: Download dotenv
        uses: actions/download-artifact@v3
        with:
          name: dotenv
      - name: Load Dotenv
        uses: xom9ikk/dotenv@v2
      - uses: actions/checkout@v4
      - name: Setup git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      - name: Create Tag
        run: git tag "v$RELEASE_VERSION"
      - name: Push tag
        run: git push origin "v$RELEASE_VERSION"
  publish-gradle:
    runs-on: ubuntu-latest
    needs:
      - create-tag
    permissions:
      contents: read
      packages: write
    steps:
      - name: Download dotenv
        uses: actions/download-artifact@v3
        with:
          name: dotenv
      - name: Load Dotenv
        uses: xom9ikk/dotenv@v2
      - uses: actions/checkout@v4
        with:
          ref: /tags/v${{ env.RELEASE_VERSION }}
      - name: Setup JDK-17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Build with Gradle
        run: chmod +rx $SCRIPT_DIR/gradle_build.sh && $SCRIPT_DIR/gradle_build.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: '*/**/libs/*.jar'
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - publish-gradle
    steps:
      - name: Download dotenv
        uses: actions/download-artifact@v3
        with:
          name: dotenv
      - name: Load Dotenv
        uses: xom9ikk/dotenv@v2
      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: binaries
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 'refs/tags/v{{ env.RELEASE_VERSION }}'
          generate_release_notes: true
          files: '*/**libs/*.jar'