# application properties
quarkus.application.name=operator

# Bundle properties
quarkus.operator-sdk.bundle.channels=preview,stable
quarkus.operator-sdk.bundle.default-channel=preview

# Operator properties
quarkus.operator-sdk.crd.apply=true
quarkus.operator-sdk.crd.validate=true
quarkus.operator-sdk.namespaces=JOSDK_WATCH_CURRENT
quarkus.operator-sdk.generate-with-watched-namespaces=JOSDK_WATCH_CURRENT

# custom properties
minecraftonk8s.operator.proxy.serviceaccount-name=${PROXY_SERVICEACCOUNT_NAME:minecraft-on-k8s-proxy}
minecraftonk8s.operator.binary-config-map.name=${BINARY_CONFIGMAP_NAME:minecraft-on-k8s-proxy-binaries}
minecraftonk8s.operator.binary-config-map.force-override=${FORCE_BINARY_CONFIGMAP_OVERRIDE:false}
minecraftonk8s.operator.binary-config-map.namespace=${KUBERNETES_NAMESPACE}

quarkus.container-image.registry=ghcr.io
quarkus.container-image.group=marfien/mc-on-k8s
