# application properties
quarkus.application.name=minecraft-on-k8s-operator
#quarkus.application.version=@project.version@

# Bundle properties
quarkus.operator-sdk.bundle.channels=preview,stable
quarkus.operator-sdk.bundle.default-channel=preview

# Operator properties
quarkus.operator-sdk.crd.apply=true
quarkus.operator-sdk.namespaces=JOSDK_WATCH_CURRENT
quarkus.operator-sdk.generate-with-watched-namespaces=JOSDK_WATCH_CURRENT

# custom properties
minecraftonk8s.proxy.serviceaccount.name=${PROXY_SERVICEACCOUNT_NAME:minecraft-on-k8s-proxy}

quarkus.container-image.registry=ghcr.io
quarkus.container-image.group=marfien/mc-on-k8s
